courses:
  interpretation:
    domain: interpretation.connectedacademy.io
    repo: https://github.com/connectedacademy/interpretation
    url: https://interpretation.connectedacademy.io
  testclass:
    domain: talkingpictures.connectedacademy.io
    repo: https://github.com/connectedacademy/talkingpictures
    url: https://talkingpictures.connectedacademy.io
  developer:
    domain: connectedacademy.io
    repo: https://github.com/connectedacademy/testclass
    url: https://testclass.connectedacademy.io
