courses:
  developer:
    domain: connectedacademy.io
    repo: https://github.com/connectedacademy/testclass
    url: https://testclass.connectedacademy.io
  testclass:
    domain: testclass.connectedacademy.io
    repo: https://github.com/connectedacademy/testclass
    url: https://testclass.connectedacademy.io
