courses:
  testclass:
    domain: testclass.connectedacademy.io
    repo: https://github.com/connectedacademy/testclass
    url: http://testclass.connectedacademy.io
  devclass:
    domain: testclass.connectedacademy.io
    repo: https://github.com/connectedacademy/testclass
    url: http://testclass.connectedacademy.io